-- Component 1: Kreisel BMS String (Debug PCAN)
INSERT INTO hardware_component (name, manufacturer, model, description, status, updated_at)
VALUES (
  'Kreisel BMS String (Debug PCAN)',
  'Kreisel Electric',
  'Battery BMS',
  'Kreisel Electric battery string — per-string data on the debug PCAN bus. Instantiate once per BMS node (01/05/09/13/17/21/25/29). CAN ID offset per node: +0=01, +1=05, +2=09, +3=13, +4=17, +5=21, +6=25, +7=29. SlowDataMpex (0x190) uses mux (page index byte).',
  'DRAFT', NOW()
) RETURNING id \gset c1_

INSERT INTO component_signal
  (component_id, channel_offset, tag_suffix, description, io_type, origin,
   can_id, bit_offset, bit_length, byte_order,
   is_mux_indicator, mux_id, active)
VALUES
  (:c1_id, 0, 'stringStateReq_BMS01_BMS', 'stringStateReq_BMS01_BMS', 'AO', 'CANBUS', 0, 3, 4, 'BIG_ENDIAN', false, NULL, true),
  (:c1_id, 1, 'isolationRequest_BMS01_BMS', 'isolationRequest_BMS01_BMS', 'AO', 'CANBUS', 0, 7, 4, 'BIG_ENDIAN', false, NULL, true),
  (:c1_id, 2, 'sleepRequest_BMS01_BMS', 'sleepRequest_BMS01_BMS', 'AO', 'CANBUS', 0, 11, 4, 'BIG_ENDIAN', false, NULL, true),
  (:c1_id, 3, 'stringOpenDEMReq_BMS01_BMS', 'stringOpenDEMReq_BMS01_BMS', 'DO', 'CANBUS', 0, 12, 1, 'BIG_ENDIAN', false, NULL, true),
  (:c1_id, 4, 'current', 'current_BMS01', 'AI', 'CANBUS', 16, 7, 16, 'BIG_ENDIAN', false, NULL, true),
  (:c1_id, 5, 'linkVoltage', 'linkVoltage_BMS01', 'AI', 'CANBUS', 16, 23, 16, 'BIG_ENDIAN', false, NULL, true),
  (:c1_id, 6, 'stringState', 'stringState_BMS01', 'AI', 'CANBUS', 16, 35, 4, 'BIG_ENDIAN', false, NULL, true),
  (:c1_id, 7, 'chargeState', 'chargeState_BMS01', 'AI', 'CANBUS', 16, 39, 4, 'BIG_ENDIAN', false, NULL, true),
  (:c1_id, 8, 'faultBitHVIL', 'faultBitHVIL_BMS01', 'DI', 'CANBUS', 16, 40, 1, 'BIG_ENDIAN', false, NULL, true),
  (:c1_id, 9, 'thermalFaultIndex', 'thermalFaultIndex_BMS01', 'AI', 'CANBUS', 16, 43, 3, 'BIG_ENDIAN', false, NULL, true),
  (:c1_id, 10, 'thermalEventStatus', 'thermalEventStatus_BMS01', 'AI', 'CANBUS', 16, 45, 2, 'BIG_ENDIAN', false, NULL, true),
  (:c1_id, 11, 'thermalEventTypeS', 'thermalEventTypeS_BMS01', 'DI', 'CANBUS', 16, 46, 1, 'BIG_ENDIAN', false, NULL, true),
  (:c1_id, 12, 'stringInitStatus', 'stringInitStatus_BMS01', 'AI', 'CANBUS', 16, 49, 2, 'BIG_ENDIAN', false, NULL, true),
  (:c1_id, 13, 'stringVoltage', 'stringVoltage_BMS01', 'AI', 'CANBUS', 32, 7, 16, 'BIG_ENDIAN', false, NULL, true),
  (:c1_id, 14, 'chargerCurrentLimit', 'chargerCurrentLimit_BMS01', 'AI', 'CANBUS', 32, 23, 16, 'BIG_ENDIAN', false, NULL, true),
  (:c1_id, 15, 'meanSOC', 'meanSOC_BMS01', 'AI', 'CANBUS', 32, 39, 16, 'BIG_ENDIAN', false, NULL, true),
  (:c1_id, 16, 'brickOpenCircuitV', 'brickOpenCircuitV_BMS01', 'AI', 'CANBUS', 32, 55, 16, 'BIG_ENDIAN', false, NULL, true),
  (:c1_id, 17, 'isolationResExternal', 'isolationResExternal_BMS01', 'AI', 'CANBUS', 48, 7, 16, 'BIG_ENDIAN', false, NULL, true),
  (:c1_id, 18, 'isolationResInternal', 'isolationResInternal_BMS01', 'AI', 'CANBUS', 48, 23, 16, 'BIG_ENDIAN', false, NULL, true),
  (:c1_id, 19, 'minSOC', 'minSOC_BMS01', 'AI', 'CANBUS', 48, 39, 16, 'BIG_ENDIAN', false, NULL, true),
  (:c1_id, 20, 'maxSOC', 'maxSOC_BMS01', 'AI', 'CANBUS', 48, 55, 16, 'BIG_ENDIAN', false, NULL, true),
  (:c1_id, 21, 'dchgIntResistance', 'dchgIntResistance_BMS01', 'AI', 'CANBUS', 64, 7, 16, 'BIG_ENDIAN', false, NULL, true),
  (:c1_id, 22, 'regenIntResistance', 'regenIntResistance_BMS01', 'AI', 'CANBUS', 64, 23, 16, 'BIG_ENDIAN', false, NULL, true),
  (:c1_id, 23, 'energyAvailable', 'energyAvailable_BMS01', 'AI', 'CANBUS', 64, 39, 16, 'BIG_ENDIAN', false, NULL, true),
  (:c1_id, 24, 'minSOH', 'minSOH_BMS01', 'AI', 'CANBUS', 64, 55, 8, 'BIG_ENDIAN', false, NULL, true),
  (:c1_id, 25, 'maxSOH', 'maxSOH_BMS01', 'AI', 'CANBUS', 64, 63, 8, 'BIG_ENDIAN', false, NULL, true),
  (:c1_id, 26, 'minBrickVoltage', 'minBrickVoltage_BMS01', 'AI', 'CANBUS', 80, 7, 16, 'BIG_ENDIAN', false, NULL, true),
  (:c1_id, 27, 'maxBrickVoltage', 'maxBrickVoltage_BMS01', 'AI', 'CANBUS', 80, 23, 16, 'BIG_ENDIAN', false, NULL, true),
  (:c1_id, 28, 'minBrickVoltageIndex', 'minBrickVoltageIndex_BMS01', 'AI', 'CANBUS', 80, 39, 16, 'BIG_ENDIAN', false, NULL, true),
  (:c1_id, 29, 'maxBrickVoltageIndex', 'maxBrickVoltageIndex_BMS01', 'AI', 'CANBUS', 80, 55, 16, 'BIG_ENDIAN', false, NULL, true),
  (:c1_id, 30, 'minModuleTempString', 'minModuleTempString_BMS01', 'AI', 'CANBUS', 96, 7, 8, 'BIG_ENDIAN', false, NULL, true),
  (:c1_id, 31, 'maxModuleTempString', 'maxModuleTempString_BMS01', 'AI', 'CANBUS', 96, 15, 8, 'BIG_ENDIAN', false, NULL, true),
  (:c1_id, 32, 'minModuleTempIndex', 'minModuleTempIndex_BMS01', 'AI', 'CANBUS', 96, 23, 8, 'BIG_ENDIAN', false, NULL, true),
  (:c1_id, 33, 'maxModuleTempIndex', 'maxModuleTempIndex_BMS01', 'AI', 'CANBUS', 96, 31, 8, 'BIG_ENDIAN', false, NULL, true),
  (:c1_id, 34, 'maxDewPointTemperature', 'maxDewPointTemperature_BMS01', 'AI', 'CANBUS', 96, 39, 8, 'BIG_ENDIAN', false, NULL, true),
  (:c1_id, 35, 'meanModuleTemperature', 'meanModuleTemperature_BMS01', 'AI', 'CANBUS', 96, 47, 8, 'BIG_ENDIAN', false, NULL, true),
  (:c1_id, 36, 'minBrickCapacity', 'minBrickCapacity_BMS01', 'AI', 'CANBUS', 96, 55, 16, 'BIG_ENDIAN', false, NULL, true),
  (:c1_id, 37, 'maxStringVLimit', 'maxStringVLimit_BMS01', 'AI', 'CANBUS', 112, 7, 16, 'BIG_ENDIAN', false, NULL, true),
  (:c1_id, 38, 'minStringVLimit', 'minStringVLimit_BMS01', 'AI', 'CANBUS', 112, 23, 16, 'BIG_ENDIAN', false, NULL, true),
  (:c1_id, 39, 'regenCurrentLimit', 'regenCurrentLimit_BMS01', 'AI', 'CANBUS', 112, 39, 16, 'BIG_ENDIAN', false, NULL, true),
  (:c1_id, 40, 'dchgCurrentLimit', 'dchgCurrentLimit_BMS01', 'AI', 'CANBUS', 112, 55, 16, 'BIG_ENDIAN', false, NULL, true),
  (:c1_id, 41, 'dchgCurrentPredShrt', 'dchgCurrentPredShrt_BMS01', 'AI', 'CANBUS', 128, 7, 16, 'BIG_ENDIAN', false, NULL, true),
  (:c1_id, 42, 'dchgCurrentPredLong', 'dchgCurrentPredLong_BMS01', 'AI', 'CANBUS', 128, 23, 16, 'BIG_ENDIAN', false, NULL, true),
  (:c1_id, 43, 'regenCurrentPredShrt', 'regenCurrentPredShrt_BMS01', 'AI', 'CANBUS', 128, 39, 16, 'BIG_ENDIAN', false, NULL, true),
  (:c1_id, 44, 'regenCurrentPredLong', 'regenCurrentPredLong_BMS01', 'AI', 'CANBUS', 128, 55, 16, 'BIG_ENDIAN', false, NULL, true),
  (:c1_id, 45, 'dchgVoltagePredShrt', 'dchgVoltagePredShrt_BMS01', 'AI', 'CANBUS', 144, 7, 16, 'BIG_ENDIAN', false, NULL, true),
  (:c1_id, 46, 'dchgVoltagePredLong', 'dchgVoltagePredLong_BMS01', 'AI', 'CANBUS', 144, 23, 16, 'BIG_ENDIAN', false, NULL, true),
  (:c1_id, 47, 'regenVoltagePredShrt', 'regenVoltagePredShrt_BMS01', 'AI', 'CANBUS', 144, 39, 16, 'BIG_ENDIAN', false, NULL, true),
  (:c1_id, 48, 'regenVoltagePredLong', 'regenVoltagePredLong_BMS01', 'AI', 'CANBUS', 144, 55, 16, 'BIG_ENDIAN', false, NULL, true),
  (:c1_id, 49, 'dchgPowerPredShrt', 'dchgPowerPredShrt_BMS01', 'AI', 'CANBUS', 160, 7, 16, 'BIG_ENDIAN', false, NULL, true),
  (:c1_id, 50, 'dchgPowerPredLong', 'dchgPowerPredLong_BMS01', 'AI', 'CANBUS', 160, 23, 16, 'BIG_ENDIAN', false, NULL, true),
  (:c1_id, 51, 'regenPowerPredShrt', 'regenPowerPredShrt_BMS01', 'AI', 'CANBUS', 160, 39, 16, 'BIG_ENDIAN', false, NULL, true),
  (:c1_id, 52, 'regenPowerPredLong', 'regenPowerPredLong_BMS01', 'AI', 'CANBUS', 160, 55, 16, 'BIG_ENDIAN', false, NULL, true),
  (:c1_id, 53, 'cusMinCellVLimit', 'cusMinCellVLimit_BMS01', 'AI', 'CANBUS', 176, 7, 16, 'BIG_ENDIAN', false, NULL, true),
  (:c1_id, 54, 'cusMaxCellVLimit', 'cusMaxCellVLimit_BMS01', 'AI', 'CANBUS', 176, 23, 16, 'BIG_ENDIAN', false, NULL, true),
  (:c1_id, 55, 'cntrWeldState', 'cntrWeldState_BMS01', 'AI', 'CANBUS', 192, 3, 4, 'BIG_ENDIAN', false, NULL, true),
  (:c1_id, 56, 'cntrState', 'cntrState_BMS01', 'AI', 'CANBUS', 192, 7, 4, 'BIG_ENDIAN', false, NULL, true),
  (:c1_id, 57, 'cntrStatePos2', 'cntrStatePos2_BMS01', 'AI', 'CANBUS', 192, 9, 2, 'BIG_ENDIAN', false, NULL, true),
  (:c1_id, 58, 'cntrStatePrechg1', 'cntrStatePrechg1_BMS01', 'AI', 'CANBUS', 192, 11, 2, 'BIG_ENDIAN', false, NULL, true),
  (:c1_id, 59, 'cntrStateNeg1', 'cntrStateNeg1_BMS01', 'AI', 'CANBUS', 192, 13, 2, 'BIG_ENDIAN', false, NULL, true),
  (:c1_id, 60, 'cntrStatePos1', 'cntrStatePos1_BMS01', 'AI', 'CANBUS', 192, 15, 2, 'BIG_ENDIAN', false, NULL, true),
  (:c1_id, 61, 'cntrStateNeg3', 'cntrStateNeg3_BMS01', 'AI', 'CANBUS', 192, 17, 2, 'BIG_ENDIAN', false, NULL, true),
  (:c1_id, 62, 'cntrStatePos3', 'cntrStatePos3_BMS01', 'AI', 'CANBUS', 192, 19, 2, 'BIG_ENDIAN', false, NULL, true),
  (:c1_id, 63, 'cntrStatePrechg2', 'cntrStatePrechg2_BMS01', 'AI', 'CANBUS', 192, 21, 2, 'BIG_ENDIAN', false, NULL, true),
  (:c1_id, 64, 'cntrStateNeg2', 'cntrStateNeg2_BMS01', 'AI', 'CANBUS', 192, 23, 2, 'BIG_ENDIAN', false, NULL, true),
  (:c1_id, 65, 'stringShutdownTimer', 'stringShutdownTimer_BMS01', 'AI', 'CANBUS', 208, 7, 16, 'BIG_ENDIAN', false, NULL, true),
  (:c1_id, 66, 'stringShutdownTarget', 'stringShutdownTarget_BMS01', 'AI', 'CANBUS', 208, 19, 4, 'BIG_ENDIAN', false, NULL, true),
  (:c1_id, 67, 'chargeEnergyAvailable', 'chargeEnergyAvailable_BMS01', 'AI', 'CANBUS', 320, 7, 16, 'BIG_ENDIAN', false, NULL, true),
  (:c1_id, 68, 'cusChrgEnrgyLifeTime', 'cusChrgEnrgyLifeTime_BMS01', 'AI', 'CANBUS', 320, 39, 16, 'BIG_ENDIAN', false, NULL, true),
  (:c1_id, 69, 'cusDschrgEnrgyLifeTime', 'cusDschrgEnrgyLifeTime_BMS01', 'AI', 'CANBUS', 320, 55, 16, 'BIG_ENDIAN', false, NULL, true),
  (:c1_id, 70, 'minSOCIndex', 'minSOCIndex_BMS01', 'AI', 'CANBUS', 336, 7, 16, 'BIG_ENDIAN', false, NULL, true),
  (:c1_id, 71, 'maxSOCIndex', 'maxSOCIndex_BMS01', 'AI', 'CANBUS', 336, 23, 16, 'BIG_ENDIAN', false, NULL, true),
  (:c1_id, 72, 'obdClearFaultMemory', 'obdClearFaultMemory_BMS01', 'AI', 'CANBUS', 352, 7, 8, 'BIG_ENDIAN', false, NULL, true),
  (:c1_id, 73, 'obdDTCId', 'obdDTCId_BMS01', 'AI', 'CANBUS', 352, 15, 8, 'BIG_ENDIAN', false, NULL, true),
  (:c1_id, 74, 'obdDTCOdometer', 'obdDTCOdometer_BMS01', 'AI', 'CANBUS', 352, 23, 16, 'BIG_ENDIAN', false, NULL, true),
  (:c1_id, 75, 'obdTestFailed', 'obdTestFailed_BMS01', 'DI', 'CANBUS', 352, 32, 1, 'BIG_ENDIAN', false, NULL, true),
  (:c1_id, 76, 'obdOccurrence', 'obdOccurrence_BMS01', 'AI', 'CANBUS', 352, 39, 7, 'BIG_ENDIAN', false, NULL, true),
  (:c1_id, 77, 'energyThroughput_KWh', 'energyThroughput_KWh_BMS01', 'AI', 'CANBUS', 384, 7, 32, 'BIG_ENDIAN', false, NULL, true),
  (:c1_id, 78, 'maxFluidPressureInlet', 'maxFluidPressureInlet_BMS01', 'AI', 'CANBUS', 384, 39, 8, 'BIG_ENDIAN', false, NULL, true),
  (:c1_id, 79, 'SlowDataMpx', 'SlowDataMpx_BMS01', 'AI', 'CANBUS', 400, 7, 8, 'BIG_ENDIAN', true, NULL, true),
  (:c1_id, 80, 'SW_VersionBL', 'SW_VersionBL_BMS01', 'AI', 'CANBUS', 400, 15, 32, 'BIG_ENDIAN', false, 4, true),
  (:c1_id, 81, 'SW_Version', 'SW_Version_BMS01', 'AI', 'CANBUS', 400, 15, 32, 'BIG_ENDIAN', false, 3, true),
  (:c1_id, 82, 'PackSerialNumber_char15', 'PackSerialNumber_char15_BMS01', 'AI', 'CANBUS', 400, 15, 8, 'BIG_ENDIAN', false, 2, true),
  (:c1_id, 83, 'PackSerialNumber_char08', 'PackSerialNumber_char08_BMS01', 'AI', 'CANBUS', 400, 15, 8, 'BIG_ENDIAN', false, 1, true),
  (:c1_id, 84, 'PackSerialNumber_char01', 'PackSerialNumber_char01_BMS01', 'AI', 'CANBUS', 400, 15, 8, 'BIG_ENDIAN', false, 0, true),
  (:c1_id, 85, 'PackSerialNumber_char16', 'PackSerialNumber_char16_BMS01', 'AI', 'CANBUS', 400, 23, 8, 'BIG_ENDIAN', false, 2, true),
  (:c1_id, 86, 'PackSerialNumber_char09', 'PackSerialNumber_char09_BMS01', 'AI', 'CANBUS', 400, 23, 8, 'BIG_ENDIAN', false, 1, true),
  (:c1_id, 87, 'PackSerialNumber_char02', 'PackSerialNumber_char02_BMS01', 'AI', 'CANBUS', 400, 23, 8, 'BIG_ENDIAN', false, 0, true),
  (:c1_id, 88, 'PackSerialNumber_char17', 'PackSerialNumber_char17_BMS01', 'AI', 'CANBUS', 400, 31, 8, 'BIG_ENDIAN', false, 2, true),
  (:c1_id, 89, 'PackSerialNumber_char10', 'PackSerialNumber_char10_BMS01', 'AI', 'CANBUS', 400, 31, 8, 'BIG_ENDIAN', false, 1, true),
  (:c1_id, 90, 'PackSerialNumber_char03', 'PackSerialNumber_char03_BMS01', 'AI', 'CANBUS', 400, 31, 8, 'BIG_ENDIAN', false, 0, true),
  (:c1_id, 91, 'PackSerialNumber_char18', 'PackSerialNumber_char18_BMS01', 'AI', 'CANBUS', 400, 39, 8, 'BIG_ENDIAN', false, 2, true),
  (:c1_id, 92, 'PackSerialNumber_char11', 'PackSerialNumber_char11_BMS01', 'AI', 'CANBUS', 400, 39, 8, 'BIG_ENDIAN', false, 1, true),
  (:c1_id, 93, 'PackSerialNumber_char04', 'PackSerialNumber_char04_BMS01', 'AI', 'CANBUS', 400, 39, 8, 'BIG_ENDIAN', false, 0, true),
  (:c1_id, 94, 'PackSerialNumber_char19', 'PackSerialNumber_char19_BMS01', 'AI', 'CANBUS', 400, 47, 8, 'BIG_ENDIAN', false, 2, true),
  (:c1_id, 95, 'PackSerialNumber_char12', 'PackSerialNumber_char12_BMS01', 'AI', 'CANBUS', 400, 47, 8, 'BIG_ENDIAN', false, 1, true),
  (:c1_id, 96, 'PackSerialNumber_char05', 'PackSerialNumber_char05_BMS01', 'AI', 'CANBUS', 400, 47, 8, 'BIG_ENDIAN', false, 0, true),
  (:c1_id, 97, 'PackSerialNumber_char20', 'PackSerialNumber_char20_BMS01', 'AI', 'CANBUS', 400, 55, 8, 'BIG_ENDIAN', false, 2, true),
  (:c1_id, 98, 'PackSerialNumber_char13', 'PackSerialNumber_char13_BMS01', 'AI', 'CANBUS', 400, 55, 8, 'BIG_ENDIAN', false, 1, true),
  (:c1_id, 99, 'PackSerialNumber_char06', 'PackSerialNumber_char06_BMS01', 'AI', 'CANBUS', 400, 55, 8, 'BIG_ENDIAN', false, 0, true),
  (:c1_id, 100, 'PackSerialNumber_char14', 'PackSerialNumber_char14_BMS01', 'AI', 'CANBUS', 400, 63, 8, 'BIG_ENDIAN', false, 1, true),
  (:c1_id, 101, 'PackSerialNumber_char07', 'PackSerialNumber_char07_BMS01', 'AI', 'CANBUS', 400, 63, 8, 'BIG_ENDIAN', false, 0, true),
  (:c1_id, 102, 'cmbCoolantTemp01', 'cmbCoolantTemp01_BMS01', 'AI', 'CANBUS', 512, 7, 8, 'BIG_ENDIAN', false, NULL, true),
  (:c1_id, 103, 'cmbCoolantTemp02', 'cmbCoolantTemp02_BMS01', 'AI', 'CANBUS', 512, 15, 8, 'BIG_ENDIAN', false, NULL, true),
  (:c1_id, 104, 'cmbCoolantTemp03', 'cmbCoolantTemp03_BMS01', 'AI', 'CANBUS', 512, 23, 8, 'BIG_ENDIAN', false, NULL, true),
  (:c1_id, 105, 'cmbCoolantTemp04', 'cmbCoolantTemp04_BMS01', 'AI', 'CANBUS', 512, 31, 8, 'BIG_ENDIAN', false, NULL, true),
  (:c1_id, 106, 'cmbCoolantTemp05', 'cmbCoolantTemp05_BMS01', 'AI', 'CANBUS', 512, 39, 8, 'BIG_ENDIAN', false, NULL, true),
  (:c1_id, 107, 'cmbCoolantTemp06', 'cmbCoolantTemp06_BMS01', 'AI', 'CANBUS', 512, 47, 8, 'BIG_ENDIAN', false, NULL, true),
  (:c1_id, 108, 'cmbCoolantTemp07', 'cmbCoolantTemp07_BMS01', 'AI', 'CANBUS', 512, 55, 8, 'BIG_ENDIAN', false, NULL, true),
  (:c1_id, 109, 'cmbCoolantTemp08', 'cmbCoolantTemp08_BMS01', 'AI', 'CANBUS', 512, 63, 8, 'BIG_ENDIAN', false, NULL, true),
  (:c1_id, 110, 'coolantInletTemperature', 'coolantInletTemperature_BMS01', 'AI', 'CANBUS', 528, 7, 8, 'BIG_ENDIAN', false, NULL, true),
  (:c1_id, 111, 'coolantOutletTemperature', 'coolantOutletTemperature_BMS01', 'AI', 'CANBUS', 528, 15, 8, 'BIG_ENDIAN', false, NULL, true);

-- Total: 112 signals

-- Component 2: Kreisel BMS ESS Master (Debug PCAN)
INSERT INTO hardware_component (name, manufacturer, model, description, status, updated_at)
VALUES (
  'Kreisel BMS ESS Master (Debug PCAN)',
  'Kreisel Electric',
  'Battery BMS',
  'Kreisel Electric ESS master controller — single-instance messages on the debug PCAN bus. Covers FKT handshake, ESS master state, config, and charge PID (muxed).',
  'DRAFT', NOW()
) RETURNING id \gset c2_

INSERT INTO component_signal
  (component_id, channel_offset, tag_suffix, description, io_type, origin,
   can_id, bit_offset, bit_length, byte_order,
   is_mux_indicator, mux_id, active)
VALUES
  (:c2_id, 0, 'fktCommand', 'fktCommand', 'AI', 'CANBUS', 368, 7, 8, 'BIG_ENDIAN', false, NULL, true),
  (:c2_id, 1, 'fktKey', 'fktKey', 'AI', 'CANBUS', 368, 15, 32, 'BIG_ENDIAN', false, NULL, true),
  (:c2_id, 2, 'fktSeed', 'fktSeed', 'AI', 'CANBUS', 369, 7, 32, 'BIG_ENDIAN', false, NULL, true),
  (:c2_id, 3, 'essMstrStr08ShouldBeOn_BMS', 'essMstrStr08ShouldBeOn_BMS', 'DI', 'CANBUS', 768, 0, 1, 'BIG_ENDIAN', false, NULL, true),
  (:c2_id, 4, 'essMstrStr09ShouldBeOn_BMS', 'essMstrStr09ShouldBeOn_BMS', 'DI', 'CANBUS', 768, 1, 1, 'BIG_ENDIAN', false, NULL, true),
  (:c2_id, 5, 'essMstrStr10ShouldBeOn_BMS', 'essMstrStr10ShouldBeOn_BMS', 'DI', 'CANBUS', 768, 2, 1, 'BIG_ENDIAN', false, NULL, true),
  (:c2_id, 6, 'essMstrStr11ShouldBeOn_BMS', 'essMstrStr11ShouldBeOn_BMS', 'DI', 'CANBUS', 768, 3, 1, 'BIG_ENDIAN', false, NULL, true),
  (:c2_id, 7, 'essMstrStr12ShouldBeOn_BMS', 'essMstrStr12ShouldBeOn_BMS', 'DI', 'CANBUS', 768, 4, 1, 'BIG_ENDIAN', false, NULL, true),
  (:c2_id, 8, 'essMstrStr13ShouldBeOn_BMS', 'essMstrStr13ShouldBeOn_BMS', 'DI', 'CANBUS', 768, 5, 1, 'BIG_ENDIAN', false, NULL, true),
  (:c2_id, 9, 'essMstrStr14ShouldBeOn_BMS', 'essMstrStr14ShouldBeOn_BMS', 'DI', 'CANBUS', 768, 6, 1, 'BIG_ENDIAN', false, NULL, true),
  (:c2_id, 10, 'essMstrStr15ShouldBeOn_BMS', 'essMstrStr15ShouldBeOn_BMS', 'DI', 'CANBUS', 768, 7, 1, 'BIG_ENDIAN', false, NULL, true),
  (:c2_id, 11, 'essMstrStr00ShouldBeOn_BMS', 'essMstrStr00ShouldBeOn_BMS', 'DI', 'CANBUS', 768, 8, 1, 'BIG_ENDIAN', false, NULL, true),
  (:c2_id, 12, 'essMstrStr01ShouldBeOn_BMS', 'essMstrStr01ShouldBeOn_BMS', 'DI', 'CANBUS', 768, 9, 1, 'BIG_ENDIAN', false, NULL, true),
  (:c2_id, 13, 'essMstrStr02ShouldBeOn_BMS', 'essMstrStr02ShouldBeOn_BMS', 'DI', 'CANBUS', 768, 10, 1, 'BIG_ENDIAN', false, NULL, true),
  (:c2_id, 14, 'essMstrStr03ShouldBeOn_BMS', 'essMstrStr03ShouldBeOn_BMS', 'DI', 'CANBUS', 768, 11, 1, 'BIG_ENDIAN', false, NULL, true),
  (:c2_id, 15, 'essMstrStr04ShouldBeOn_BMS', 'essMstrStr04ShouldBeOn_BMS', 'DI', 'CANBUS', 768, 12, 1, 'BIG_ENDIAN', false, NULL, true),
  (:c2_id, 16, 'essMstrStr05ShouldBeOn_BMS', 'essMstrStr05ShouldBeOn_BMS', 'DI', 'CANBUS', 768, 13, 1, 'BIG_ENDIAN', false, NULL, true),
  (:c2_id, 17, 'essMstrStr06ShouldBeOn_BMS', 'essMstrStr06ShouldBeOn_BMS', 'DI', 'CANBUS', 768, 14, 1, 'BIG_ENDIAN', false, NULL, true),
  (:c2_id, 18, 'essMstrStr07ShouldBeOn_BMS', 'essMstrStr07ShouldBeOn_BMS', 'DI', 'CANBUS', 768, 15, 1, 'BIG_ENDIAN', false, NULL, true),
  (:c2_id, 19, 'essShutdownTimer_BMS', 'essShutdownTimer_BMS', 'AI', 'CANBUS', 768, 23, 16, 'BIG_ENDIAN', false, NULL, true),
  (:c2_id, 20, 'essShutdownTarget_BMS', 'essShutdownTarget_BMS', 'AI', 'CANBUS', 768, 35, 4, 'BIG_ENDIAN', false, NULL, true),
  (:c2_id, 21, 'essMstrStateRequest_BMS', 'essMstrStateRequest_BMS', 'AI', 'CANBUS', 768, 43, 4, 'BIG_ENDIAN', false, NULL, true),
  (:c2_id, 22, 'essMstrNrOfStringsInPrchg_BMS', 'essMstrNrOfStringsInPrchg_BMS', 'AI', 'CANBUS', 768, 47, 4, 'BIG_ENDIAN', false, NULL, true),
  (:c2_id, 23, 'essMstrOverallChargeState_BMS', 'essMstrOverallChargeState_BMS', 'AI', 'CANBUS', 768, 51, 4, 'BIG_ENDIAN', false, NULL, true),
  (:c2_id, 24, 'essMstrState_BMS01', 'essMstrState_BMS01', 'AI', 'CANBUS', 768, 55, 4, 'BIG_ENDIAN', false, NULL, true),
  (:c2_id, 25, 'essMstrDriveInhibit_BMS', 'essMstrDriveInhibit_BMS', 'DI', 'CANBUS', 768, 56, 1, 'BIG_ENDIAN', false, NULL, true),
  (:c2_id, 26, 'essMstrChargeInhibit_BMS', 'essMstrChargeInhibit_BMS', 'DI', 'CANBUS', 768, 57, 1, 'BIG_ENDIAN', false, NULL, true),
  (:c2_id, 27, 'essMstrAccInhibit_BMS', 'essMstrAccInhibit_BMS', 'DI', 'CANBUS', 768, 58, 1, 'BIG_ENDIAN', false, NULL, true),
  (:c2_id, 28, 'essMstrChargeDerateFlag_BMS', 'essMstrChargeDerateFlag_BMS', 'DI', 'CANBUS', 768, 59, 1, 'BIG_ENDIAN', false, NULL, true),
  (:c2_id, 29, 'essMstrPrechargeState14_BMS', 'essMstrPrechargeState14_BMS', 'AI', 'CANBUS', 769, 3, 4, 'BIG_ENDIAN', false, NULL, true),
  (:c2_id, 30, 'essMstrPrechargeState15_BMS', 'essMstrPrechargeState15_BMS', 'AI', 'CANBUS', 769, 7, 4, 'BIG_ENDIAN', false, NULL, true),
  (:c2_id, 31, 'essMstrPrechargeState12_BMS', 'essMstrPrechargeState12_BMS', 'AI', 'CANBUS', 769, 11, 4, 'BIG_ENDIAN', false, NULL, true),
  (:c2_id, 32, 'essMstrPrechargeState13_BMS', 'essMstrPrechargeState13_BMS', 'AI', 'CANBUS', 769, 15, 4, 'BIG_ENDIAN', false, NULL, true),
  (:c2_id, 33, 'essMstrPrechargeState10_BMS', 'essMstrPrechargeState10_BMS', 'AI', 'CANBUS', 769, 19, 4, 'BIG_ENDIAN', false, NULL, true),
  (:c2_id, 34, 'essMstrPrechargeState11_BMS', 'essMstrPrechargeState11_BMS', 'AI', 'CANBUS', 769, 23, 4, 'BIG_ENDIAN', false, NULL, true),
  (:c2_id, 35, 'essMstrPrechargeState08_BMS', 'essMstrPrechargeState08_BMS', 'AI', 'CANBUS', 769, 27, 4, 'BIG_ENDIAN', false, NULL, true),
  (:c2_id, 36, 'essMstrPrechargeState09_BMS', 'essMstrPrechargeState09_BMS', 'AI', 'CANBUS', 769, 31, 4, 'BIG_ENDIAN', false, NULL, true),
  (:c2_id, 37, 'essMstrPrechargeState06_BMS', 'essMstrPrechargeState06_BMS', 'AI', 'CANBUS', 769, 35, 4, 'BIG_ENDIAN', false, NULL, true),
  (:c2_id, 38, 'essMstrPrechargeState07_BMS', 'essMstrPrechargeState07_BMS', 'AI', 'CANBUS', 769, 39, 4, 'BIG_ENDIAN', false, NULL, true),
  (:c2_id, 39, 'essMstrPrechargeState04_BMS', 'essMstrPrechargeState04_BMS', 'AI', 'CANBUS', 769, 43, 4, 'BIG_ENDIAN', false, NULL, true),
  (:c2_id, 40, 'essMstrPrechargeState05_BMS', 'essMstrPrechargeState05_BMS', 'AI', 'CANBUS', 769, 47, 4, 'BIG_ENDIAN', false, NULL, true),
  (:c2_id, 41, 'essMstrPrechargeState02_BMS', 'essMstrPrechargeState02_BMS', 'AI', 'CANBUS', 769, 51, 4, 'BIG_ENDIAN', false, NULL, true),
  (:c2_id, 42, 'essMstrPrechargeState03_BMS', 'essMstrPrechargeState03_BMS', 'AI', 'CANBUS', 769, 55, 4, 'BIG_ENDIAN', false, NULL, true),
  (:c2_id, 43, 'essMstrPrechargeState00_BMS', 'essMstrPrechargeState00_BMS', 'AI', 'CANBUS', 769, 59, 4, 'BIG_ENDIAN', false, NULL, true),
  (:c2_id, 44, 'essMstrPrechargeState01_BMS', 'essMstrPrechargeState01_BMS', 'AI', 'CANBUS', 769, 63, 4, 'BIG_ENDIAN', false, NULL, true),
  (:c2_id, 45, 'numberOfPacksPerString_BMS', 'numberOfPacksPerString_BMS', 'AI', 'CANBUS', 771, 2, 3, 'BIG_ENDIAN', false, NULL, true),
  (:c2_id, 46, 'numberOfStrings_BMS', 'numberOfStrings_BMS', 'AI', 'CANBUS', 771, 7, 5, 'BIG_ENDIAN', false, NULL, true),
  (:c2_id, 47, 'numberOfModulesPerPack_BMS', 'numberOfModulesPerPack_BMS', 'AI', 'CANBUS', 771, 15, 8, 'BIG_ENDIAN', false, NULL, true),
  (:c2_id, 48, 'numberOfCellsPerModule_BMS', 'numberOfCellsPerModule_BMS', 'AI', 'CANBUS', 771, 23, 8, 'BIG_ENDIAN', false, NULL, true),
  (:c2_id, 49, 'debugChargePIDMpex_BMS01', 'debugChargePIDMpex_BMS01', 'AI', 'CANBUS', 772, 7, 8, 'BIG_ENDIAN', true, NULL, true),
  (:c2_id, 50, 'PID_loadCurrrentPID_error_BMS', 'PID_loadCurrrentPID_error_BMS', 'AI', 'CANBUS', 772, 15, 8, 'BIG_ENDIAN', false, 2, true),
  (:c2_id, 51, 'PID_StringCurrrentPID_error_BMS', 'PID_StringCurrrentPID_error_BMS', 'AI', 'CANBUS', 772, 15, 8, 'BIG_ENDIAN', false, 1, true),
  (:c2_id, 52, 'PID_BrickVPID_error_BMS', 'PID_BrickVPID_error_BMS', 'AI', 'CANBUS', 772, 15, 8, 'BIG_ENDIAN', false, 0, true),
  (:c2_id, 53, 'PID_loadCurrrentPID_int_BMS', 'PID_loadCurrrentPID_int_BMS', 'AI', 'CANBUS', 772, 23, 8, 'BIG_ENDIAN', false, 2, true),
  (:c2_id, 54, 'PID_StringCurrrentPID_int_BMS', 'PID_StringCurrrentPID_int_BMS', 'AI', 'CANBUS', 772, 23, 8, 'BIG_ENDIAN', false, 1, true),
  (:c2_id, 55, 'PID_BrickVPID_int_BMS', 'PID_BrickVPID_int_BMS', 'AI', 'CANBUS', 772, 23, 8, 'BIG_ENDIAN', false, 0, true),
  (:c2_id, 56, 'PID_loadCurrrentPID_out_BMS', 'PID_loadCurrrentPID_out_BMS', 'AI', 'CANBUS', 772, 31, 16, 'BIG_ENDIAN', false, 2, true),
  (:c2_id, 57, 'PID_StringCurrrentPID_out_BMS', 'PID_StringCurrrentPID_out_BMS', 'AI', 'CANBUS', 772, 31, 16, 'BIG_ENDIAN', false, 1, true),
  (:c2_id, 58, 'PID_BrickVPID_out_BMS', 'PID_BrickVPID_out_BMS', 'AI', 'CANBUS', 772, 31, 16, 'BIG_ENDIAN', false, 0, true);

-- Total: 59 signals