-- No-op migration. The original file was contaminated with dotenv stdout
-- noise from a Prisma diff invocation; the actual schema delta was empty
-- (later migrations carried the real changes). Kept for migration-history
-- continuity so prisma migrate deploy doesn't see a re-numbered chain.
